# Generated by Django 5.0.6 on 2024-07-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_drama_subjectmarks_acting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectmarks',
            old_name='english',
            new_name='language_1',
        ),
        migrations.RenameField(
            model_name='subjectmarks',
            old_name='tamil',
            new_name='language_2',
        ),
    ]
